# @package _group_

# this should only contain the decoder part, the encoder part is in encoder.yaml
cfg_adjuster:
  _target_: rxnrep.model.regressor.adjust_config

model_class:
  _target_: rxnrep.model.regressor.LightningModel
  property_name: [reaction_energy] # a list of regression properties
  regression_decoder_num_layers: [2] # a list of decoder sizes, one fro each property
